# Generated by Django 4.0.3 on 2022-04-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('TableID', models.AutoField(primary_key=True, serialize=False)),
                ('TableName', models.CharField(max_length=500)),
            ],
        ),
    ]
