# Generated by Django 4.0.3 on 2022-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_history_table_tablenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('FileID', models.AutoField(primary_key=True, serialize=False)),
                ('HistoryID', models.IntegerField()),
                ('Atribute', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LastSession',
            fields=[
                ('LastSessionID', models.AutoField(primary_key=True, serialize=False)),
                ('HistoryID', models.IntegerField()),
                ('WebUserID', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='Date',
        ),
        migrations.AddField(
            model_name='history',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='DateModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
